server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  mustache:
    servlet:
      expose-request-attributes: true
      expose-session-attributes: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create # none, update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/data.sql
oauth:
  kakao:
    client-id: 160cd4f66fc928d2b279d78999d6d018
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: oCftA1myO0
    client-id: wkI_0iNs7BmVF5O9ZLr1
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
